# Generated by Django 3.2 on 2021-04-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='security_access_level',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
