# Generated by Django 3.2 on 2021-04-19 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipments', '0002_auto_20210419_1505'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('request_id', models.IntegerField()),
                ('request_granted', models.BooleanField()),
                ('actioned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actioned_by', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipmentmodel')),
                ('requested_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Model',
            },
        ),
        migrations.CreateModel(
            name='IssueBookModel',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('actioned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipmentmodel')),
                ('requested_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IssueBook Model',
            },
        ),
    ]
