# Generated by Django 3.2 on 2021-04-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='equipment_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
